# Generated by Django 5.2.5 on 2026-07-27 20:37

import accounts.managers
import accounts.utils
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=11, unique=True, validators=[accounts.utils.validate_iranian_phone], verbose_name='شماره موبایل')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='نام و نام خانوادگی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='عضو تیم')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ عضویت')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=11, validators=[accounts.utils.validate_iranian_phone], verbose_name='شماره موبایل')),
                ('code_hash', models.CharField(editable=False, max_length=255, verbose_name='هش کد')),
                ('expires_at', models.DateTimeField(verbose_name='زمان انقضا')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'درخواست کد یکبار مصرف',
                'verbose_name_plural': 'درخواست\u200cهای کد یکبار مصرف',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'is_used', '-created_at'], name='otp_phone_active_idx')],
            },
        ),
    ]
