# Generated by Django 5.2.5 on 2026-07-29 12:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='نامک')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='نام')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='نامک')),
                ('flower_type', models.CharField(max_length=120, verbose_name='نوع گل')),
                ('color', models.CharField(blank=True, max_length=80, verbose_name='رنگ')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('stems_per_bundle', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد شاخه در دسته')),
                ('price_per_bundle', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='قیمت هر دسته (تومان)')),
                ('stock_bundles', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='موجودی دسته')),
                ('minimum_order_bundles', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='حداقل سفارش دسته')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='products/covers/', verbose_name='تصویر اصلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=180, verbose_name='متن جایگزین')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
