# Generated by Django 5.2.5 on 2026-08-02 10:00

import django.core.validators
from django.db import migrations, models


def seed_indoor_plants_category(apps, schema_editor) -> None:
    from products.seeding import ensure_indoor_plants_category

    category_model = apps.get_model("products", "Category")
    ensure_indoor_plants_category(category_model)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_store_product_image_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='product',
            name='care_difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'حساس')], max_length=20, verbose_name='سختی نگهداری'),
        ),
        migrations.AddField(
            model_name='product',
            name='care_tips',
            field=models.TextField(blank=True, verbose_name='نکات نگهداری'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_notes',
            field=models.CharField(blank=True, max_length=250, verbose_name='نکات ارسال'),
        ),
        migrations.AddField(
            model_name='product',
            name='ideal_temperature',
            field=models.CharField(blank=True, max_length=50, verbose_name='دمای ایده\u200cآل'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_pet_friendly',
            field=models.BooleanField(blank=True, null=True, verbose_name='سازگار با حیوانات خانگی'),
        ),
        migrations.AddField(
            model_name='product',
            name='light_requirement',
            field=models.CharField(blank=True, max_length=100, verbose_name='نیاز نوری'),
        ),
        migrations.AddField(
            model_name='product',
            name='plant_height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='ارتفاع تقریبی گیاه (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='product',
            name='plant_size',
            field=models.CharField(blank=True, max_length=50, verbose_name='اندازه گیاه'),
        ),
        migrations.AddField(
            model_name='product',
            name='pot_color',
            field=models.CharField(blank=True, max_length=50, verbose_name='رنگ گلدان'),
        ),
        migrations.AddField(
            model_name='product',
            name='pot_has_drainage',
            field=models.BooleanField(blank=True, null=True, verbose_name='دارای زهکشی'),
        ),
        migrations.AddField(
            model_name='product',
            name='pot_included',
            field=models.BooleanField(default=True, verbose_name='گلدان همراه'),
        ),
        migrations.AddField(
            model_name='product',
            name='pot_material',
            field=models.CharField(blank=True, max_length=50, verbose_name='جنس گلدان'),
        ),
        migrations.AddField(
            model_name='product',
            name='pot_size_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='اندازه گلدان (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='product',
            name='quality_grade',
            field=models.CharField(blank=True, choices=[('standard', 'استاندارد'), ('premium', 'ممتاز'), ('luxury', 'لوکس')], max_length=20, verbose_name='درجه کیفیت'),
        ),
        migrations.AddField(
            model_name='product',
            name='watering_requirement',
            field=models.CharField(blank=True, max_length=100, verbose_name='نیاز آبیاری'),
        ),
        migrations.RunPython(
            seed_indoor_plants_category,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
