# Generated by Django 5.2.5 on 2026-08-02 10:31

from pathlib import PurePosixPath

import products.validators
from django.db import migrations, models


def normalize_category_image_filenames(apps, schema_editor) -> None:
    category_model = apps.get_model("products", "Category")

    for category in category_model.objects.exclude(image__isnull=True).exclude(
        image="",
    ):
        normalized = category.image.replace("\\", "/").rstrip("/")
        category.image = PurePosixPath(normalized).name
        category.save(update_fields=("image",))


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_indoor_plant_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, help_text='نام فایل موجود در web/public/images/categories را وارد کنید؛ مانند florisa-indoor-plants-category.png', max_length=255, null=True, validators=[products.validators.validate_repository_image_path], verbose_name='تصویر'),
        ),
        migrations.RunPython(
            normalize_category_image_filenames,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
