# Generated by Django 5.2.5 on 2026-08-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_assign_remaining_plant_webp_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_title', models.CharField(help_text='فقط برای شناسایی اسلاید در پنل مدیریت نمایش داده می\u200cشود.', max_length=120, verbose_name='عنوان داخلی')),
                ('eyebrow', models.CharField(blank=True, max_length=80, verbose_name='متن بالای عنوان')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان اصلی')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='توضیح کوتاه')),
                ('mobile_image', models.ImageField(help_text='تصویر عمودی با نسبت حدود ۳:۴ (برای نمونه ۹۰۰×۱۲۰۰) پیشنهاد می\u200cشود؛ سوژه و فضای امن متن را در مرکز نگه دارید.', upload_to='home/slides/mobile/%Y/%m/', verbose_name='تصویر موبایل')),
                ('desktop_image', models.ImageField(help_text='تصویر عریض با نسبت حدود ۸:۳ (برای نمونه ۱۶۰۰×۶۰۰) پیشنهاد می\u200cشود؛ سوژه و فضای امن متن را در مرکز نگه دارید.', upload_to='home/slides/desktop/%Y/%m/', verbose_name='تصویر دسکتاپ')),
                ('image_alt', models.CharField(help_text='تصویر را کوتاه و معنادار برای کاربران صفحه\u200cخوان توصیف کنید.', max_length=180, verbose_name='متن جایگزین تصویر')),
                ('cta_label', models.CharField(blank=True, max_length=60, verbose_name='متن دکمه')),
                ('cta_url', models.CharField(blank=True, help_text='فقط مسیر داخلی فلوریسا را وارد کنید؛ مانند /shop?category=plants.', max_length=500, verbose_name='مقصد دکمه')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'اسلاید خانه',
                'verbose_name_plural': 'اسلایدهای خانه',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
