# Generated by Django 5.2.5 on 2026-09-04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_homeslide"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homeslide",
            name="description",
        ),
        migrations.RemoveField(
            model_name="homeslide",
            name="eyebrow",
        ),
        migrations.AddField(
            model_name="homeslide",
            name="button_background_color",
            field=models.CharField(
                default="#d4af37",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="رنگ باید با فرمت هگزادسیمال مانند #d4af37 وارد شود.",
                        regex="^#[0-9a-fA-F]{6}$",
                    )
                ],
                verbose_name="رنگ پس‌زمینه دکمه",
            ),
        ),
        migrations.AddField(
            model_name="homeslide",
            name="button_text_color",
            field=models.CharField(
                default="#121212",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="رنگ باید با فرمت هگزادسیمال مانند #121212 وارد شود.",
                        regex="^#[0-9a-fA-F]{6}$",
                    )
                ],
                verbose_name="رنگ متن دکمه",
            ),
        ),
    ]
