# Generated by Django 5.2.5 on 2026-09-04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_homeslide_button_colors_remove_unused_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeslide",
            name="title_text_color",
            field=models.CharField(
                default="#ffffff",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="رنگ باید با فرمت هگزادسیمال مانند #ffffff وارد شود.",
                        regex="^#[0-9a-fA-F]{6}$",
                    )
                ],
                verbose_name="رنگ متن عنوان",
            ),
        ),
    ]
