# Generated by Django 5.2.5 on 2026-09-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_homeslide_title_text_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="featured_order",
            field=models.PositiveIntegerField(
                default=0,
                verbose_name="ترتیب نمایش ویژه",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_featured", "featured_order", "id"],
                name="product_featured_order_idx",
            ),
        ),
    ]
