# Generated by Django 5.2.5 on 2026-09-09 06:48

import media_store.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_featured_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_upload',
            field=media_store.fields.UploadImageField(blank=True, help_text='JPG / PNG / WebP، حداکثر ۵ مگابایت؛ جایگزین تصویر اصلی می\u200cشود.', upload_to='products/covers/%Y/%m/', verbose_name='آپلود تصویر اصلی'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_upload',
            field=media_store.fields.UploadImageField(blank=True, help_text='JPG / PNG / WebP، حداکثر ۵ مگابایت؛ جایگزین مسیر تصویر می\u200cشود.', upload_to='products/images/%Y/%m/', verbose_name='آپلود تصویر'),
        ),
        migrations.AlterField(
            model_name='homeslide',
            name='desktop_image',
            field=media_store.fields.UploadImageField(help_text='تصویر عریض با نسبت حدود ۸:۳ (برای نمونه ۱۶۰۰×۶۰۰) پیشنهاد می\u200cشود؛ سوژه و فضای امن متن را در مرکز نگه دارید.', upload_to='home/slides/desktop/%Y/%m/', verbose_name='تصویر دسکتاپ'),
        ),
        migrations.AlterField(
            model_name='homeslide',
            name='mobile_image',
            field=media_store.fields.UploadImageField(help_text='تصویر عمودی با نسبت حدود ۳:۴ (برای نمونه ۹۰۰×۱۲۰۰) پیشنهاد می\u200cشود؛ سوژه و فضای امن متن را در مرکز نگه دارید.', upload_to='home/slides/mobile/%Y/%m/', verbose_name='تصویر موبایل'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.CharField(blank=True, max_length=255, verbose_name='مسیر تصویر موجود'),
        ),
    ]
