# Generated by Django 5.2.5 on 2026-09-13 10:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_cover_upload_productimage_image_upload_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=150, verbose_name='نام نویسنده')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('comment', models.TextField(verbose_name='متن دیدگاه')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('demo_key', models.CharField(blank=True, editable=False, max_length=80, null=True, unique=True, verbose_name='شناسه دیدگاه نمایشی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='محصول')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دیدگاه محصول',
                'verbose_name_plural': 'دیدگاه\u200cهای محصولات',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['product', 'is_approved', '-created_at', '-id'], name='prod_review_visible_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='product_review_rating_1_5')],
            },
        ),
    ]
