# Generated by Django 5.2.5 on 2026-09-30 21:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrangement',
            fields=[
            ],
            options={
                'verbose_name': 'گل\u200cآرایی',
                'verbose_name_plural': 'گل\u200cآرایی\u200cها',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.AddField(
            model_name='cutflowerdetails',
            name='bloom_opening_stage',
            field=models.CharField(blank=True, choices=[('closed', 'غنچه بسته'), ('semi_open', 'نیمه\u200cباز'), ('open', 'باز'), ('mixed', 'ترکیبی')], max_length=20, verbose_name='مرحله بازشدگی گل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('plant', 'گیاه'), ('arrangement', 'گل\u200cآرایی'), ('cut_flower', 'گل شاخه\u200cای')], db_index=True, max_length=20, verbose_name='نوع محصول'),
        ),
        migrations.CreateModel(
            name='ArrangementDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrangement_type', models.CharField(choices=[('bouquet', 'دسته\u200cگل'), ('flower_box', 'باکس گل'), ('basket', 'سبد گل')], max_length=20, verbose_name='نوع گل\u200cآرایی')),
                ('approximate_dimensions', models.CharField(blank=True, max_length=120, verbose_name='ابعاد تقریبی')),
                ('dominant_color_theme', models.CharField(blank=True, max_length=120, verbose_name='تم رنگی غالب')),
                ('design_style', models.CharField(blank=True, max_length=120, verbose_name='سبک طراحی')),
                ('care_notes', models.TextField(blank=True, verbose_name='نکات نگهداری')),
                ('shipping_notes', models.TextField(blank=True, verbose_name='نکات ارسال')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arrangement_details', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مشخصات گل\u200cآرایی',
                'verbose_name_plural': 'مشخصات گل\u200cآرایی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ArrangementComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=180, verbose_name='عنوان')),
                ('stem_count', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد شاخه')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('arrangement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='products.arrangementdetails', verbose_name='گل\u200cآرایی')),
            ],
            options={
                'verbose_name': 'جزء گل\u200cآرایی',
                'verbose_name_plural': 'اجزای گل\u200cآرایی',
                'ordering': ('sort_order', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('stem_count__gte', 1), ('stem_count__isnull', True), _connector='OR'), name='arrangement_composition_stem_count_positive')],
            },
        ),
        migrations.CreateModel(
            name='CutFlowerVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=80, verbose_name='رنگ')),
                ('price', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت هر واحد فروش (تومان)')),
                ('stock_quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='موجودی واحد فروش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cut_flower_variants', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تنوع رنگ گل شاخه\u200cای',
                'verbose_name_plural': 'تنوع\u200cهای رنگ گل شاخه\u200cای',
                'ordering': ('id',),
                'constraints': [models.UniqueConstraint(fields=('product', 'color'), name='unique_cut_flower_color'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='cut_flower_variant_price_nonnegative'), models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='cut_flower_variant_stock_nonnegative')],
            },
        ),
    ]
