# Generated by Django 5.2.5 on 2026-10-10 19:15

import django.db.models.deletion
import media_store.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_seed_cut_flower_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantPotAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_price', models.PositiveBigIntegerField(default=0, verbose_name='هزینه اضافی (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('combination_image', media_store.fields.UploadImageField(blank=True, upload_to='plants/pot-combinations/%Y/%m/', verbose_name='تصویر همین گیاه در این گلدان')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pot_assignments', to='products.product', verbose_name='گیاه')),
            ],
            options={
                'verbose_name': 'گلدان سازگار گیاه',
                'verbose_name_plural': 'گلدان\u200cهای سازگار گیاه',
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='plantdetails',
            name='initial_pot_assignment',
            field=models.ForeignKey(blank=True, help_text='خالی: اولین گلدان تزئینی موجود، سپس گلدان پلاستیکی پایه.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_for', to='products.plantpotassignment', verbose_name='گلدان انتخاب\u200cشده اولیه'),
        ),
        migrations.CreateModel(
            name='Pot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='نام')),
                ('material', models.CharField(blank=True, max_length=80, verbose_name='جنس')),
                ('color', models.CharField(blank=True, max_length=80, verbose_name='رنگ')),
                ('diameter_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='قطر (سانتی\u200cمتر)')),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ارتفاع (سانتی\u200cمتر)')),
                ('image', media_store.fields.UploadImageField(blank=True, upload_to='pots/%Y/%m/', verbose_name='تصویر گلدان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='موجودی مشترک')),
            ],
            options={
                'verbose_name': 'گلدان تزئینی',
                'verbose_name_plural': 'گلدان\u200cهای تزئینی',
                'ordering': ('name', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='pot_stock_nonnegative')],
            },
        ),
        migrations.AddField(
            model_name='plantpotassignment',
            name='pot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_assignments', to='products.pot', verbose_name='گلدان'),
        ),
        migrations.AddConstraint(
            model_name='plantpotassignment',
            constraint=models.UniqueConstraint(fields=('product', 'pot'), name='unique_plant_pot'),
        ),
        migrations.AddConstraint(
            model_name='plantpotassignment',
            constraint=models.CheckConstraint(condition=models.Q(('additional_price__gte', 0)), name='plant_pot_price_nonnegative'),
        ),
    ]
