# Generated by Django 5.2.5 on 2026-08-04 18:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_assign_remaining_plant_webp_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_number', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شماره سفارش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('confirmed', 'تأیید شده'), ('preparing', 'در حال آماده\u200cسازی'), ('out_for_delivery', 'در مسیر ارسال'), ('delivered', 'تحویل شده'), ('canceled', 'لغو شده')], default='pending', max_length=24, verbose_name='وضعیت سفارش')),
                ('payment_method', models.CharField(choices=[('cash_on_delivery', 'پرداخت در محل')], default='cash_on_delivery', editable=False, max_length=24, verbose_name='روش پرداخت')),
                ('payment_status', models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('paid', 'پرداخت شده')], default='unpaid', max_length=16, verbose_name='وضعیت پرداخت')),
                ('subtotal', models.DecimalField(decimal_places=0, editable=False, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='جمع کالاها')),
                ('delivery_fee', models.DecimalField(decimal_places=0, editable=False, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='هزینه ارسال')),
                ('total', models.DecimalField(decimal_places=0, editable=False, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ نهایی')),
                ('address_title', models.CharField(blank=True, editable=False, max_length=80, verbose_name='عنوان نشانی')),
                ('recipient_name', models.CharField(editable=False, max_length=150, verbose_name='نام تحویل\u200cگیرنده')),
                ('recipient_phone', models.CharField(editable=False, max_length=11, verbose_name='شماره تحویل\u200cگیرنده')),
                ('province', models.CharField(editable=False, max_length=80, verbose_name='استان')),
                ('city', models.CharField(editable=False, max_length=80, verbose_name='شهر')),
                ('district', models.CharField(blank=True, editable=False, max_length=120, verbose_name='منطقه یا محله')),
                ('address_line', models.CharField(editable=False, max_length=500, verbose_name='نشانی')),
                ('plaque', models.CharField(blank=True, editable=False, max_length=20, verbose_name='پلاک')),
                ('unit', models.CharField(blank=True, editable=False, max_length=20, verbose_name='واحد')),
                ('postal_code', models.CharField(blank=True, editable=False, max_length=10, verbose_name='کد پستی')),
                ('delivery_note', models.CharField(blank=True, editable=False, max_length=500, verbose_name='توضیحات تحویل')),
                ('customer_note', models.CharField(blank=True, editable=False, max_length=500, verbose_name='یادداشت مشتری')),
                ('idempotency_key', models.UUIDField(editable=False, verbose_name='شناسه درخواست')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(editable=False, max_length=180, verbose_name='نام محصول')),
                ('product_type', models.CharField(editable=False, max_length=20, verbose_name='نوع محصول')),
                ('sale_unit', models.CharField(editable=False, max_length=20, verbose_name='واحد فروش')),
                ('sale_unit_display', models.CharField(editable=False, max_length=40, verbose_name='عنوان واحد فروش')),
                ('unit_size', models.PositiveIntegerField(editable=False, verbose_name='تعداد در واحد')),
                ('quantity', models.PositiveIntegerField(editable=False, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=0, editable=False, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت واحد')),
                ('line_total', models.DecimalField(decimal_places=0, editable=False, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='جمع ردیف')),
                ('cover_image', models.CharField(blank=True, editable=False, max_length=255, verbose_name='تصویر محصول')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'قلم سفارش',
                'verbose_name_plural': 'اقلام سفارش',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80, verbose_name='عنوان')),
                ('recipient_name', models.CharField(max_length=150, verbose_name='نام تحویل\u200cگیرنده')),
                ('recipient_phone', models.CharField(max_length=11, verbose_name='شماره تحویل\u200cگیرنده')),
                ('province', models.CharField(default='تهران', max_length=80, verbose_name='استان')),
                ('city', models.CharField(default='تهران', max_length=80, verbose_name='شهر')),
                ('district', models.CharField(blank=True, max_length=120, verbose_name='منطقه یا محله')),
                ('address_line', models.CharField(max_length=500, verbose_name='نشانی')),
                ('plaque', models.CharField(blank=True, max_length=20, verbose_name='پلاک')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='واحد')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='کد پستی')),
                ('delivery_note', models.CharField(blank=True, max_length=500, verbose_name='توضیحات تحویل')),
                ('is_default', models.BooleanField(default=False, verbose_name='نشانی پیش\u200cفرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نشانی کاربر',
                'verbose_name_plural': 'نشانی\u200cهای کاربران',
                'ordering': ('-is_default', '-updated_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='unique_checkout_request_per_user'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('delivery_fee__gte', 0), ('total__gte', 0)), name='order_totals_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique_product_per_order'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='order_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0), ('line_total__gte', 0)), name='order_item_totals_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='useraddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='one_default_address_per_user'),
        ),
    ]
