# Generated by Django 5.2.5 on 2026-09-30 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0015_arrangement_cutflowerdetails_bloom_opening_stage_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique_product_per_order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.cutflowervariant', verbose_name='تنوع رنگ'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_color',
            field=models.CharField(blank=True, editable=False, max_length=80, verbose_name='رنگ در زمان سفارش'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_id_snapshot',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True, verbose_name='شناسه تنوع در زمان سفارش'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True), ('variant_id_snapshot__isnull', True)), fields=('order', 'product'), name='unique_unvaried_product_per_order'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('order', 'product', 'variant'), name='unique_product_variant_per_order'),
        ),
    ]
