# Generated by Django 5.2.5 on 2026-10-10 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_unique_product_per_order_and_more'),
        ('products', '0017_plantpotassignment_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique_unvaried_product_per_order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pot_assignment',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.plantpotassignment'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pot_attributes',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pot_id_snapshot',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pot_name',
            field=models.CharField(blank=True, editable=False, max_length=180, verbose_name='گلدان سفارش'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pot_option_id_snapshot',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pot_surcharge',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(condition=models.Q(('pot_option_id_snapshot__isnull', True), ('variant__isnull', True), ('variant_id_snapshot__isnull', True)), fields=('order', 'product'), name='unique_unvaried_product_per_order'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(condition=models.Q(('pot_option_id_snapshot__isnull', False)), fields=('order', 'product', 'pot_option_id_snapshot'), name='unique_order_plant_pot_option'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('pot_surcharge__gte', 0)), name='order_pot_surcharge_nonnegative'),
        ),
    ]
