# Generated by Django 5.2.5 on 2026-09-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('content', models.BinaryField()),
                ('content_type', models.CharField(max_length=32)),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
