# Generated by Django 5.2.5 on 2026-09-08 18:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0012_product_featured_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='نامک')),
                ('excerpt', models.CharField(blank=True, max_length=300, verbose_name='خلاصه')),
                ('cover_image', models.ImageField(blank=True, upload_to='magazine/covers/%Y/%m/', verbose_name='تصویر اصلی')),
                ('content', models.JSONField(blank=True, default=list, help_text='آرایه\u200cای از بلوک\u200cها؛ مانند [{"type": "paragraph", "text": "متن مقاله"}]. متن ساده وارد کنید؛ HTML لازم نیست.', verbose_name='محتوا')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار')),
                ('reading_time', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='زمان مطالعه (دقیقه)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شود')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ('-published_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='MagazineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='نامک')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی مجله',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای مجله',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ArticleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='magazine.article', verbose_name='مقاله')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magazine_links', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'محصول مرتبط',
                'verbose_name_plural': 'محصولات مرتبط',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='magazine_articles', through='magazine.ArticleProduct', to='products.product', verbose_name='محصولات مرتبط'),
        ),
        migrations.CreateModel(
            name='ArticleRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_links', to='magazine.article', verbose_name='مقاله')),
                ('related_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_article_links', to='magazine.article', verbose_name='مقاله مرتبط')),
            ],
            options={
                'verbose_name': 'مقاله مرتبط',
                'verbose_name_plural': 'مقالات مرتبط',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='related_articles',
            field=models.ManyToManyField(blank=True, related_name='recommended_by_articles', through='magazine.ArticleRelation', through_fields=('article', 'related_article'), to='magazine.article', verbose_name='مقالات مرتبط'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='magazine.magazinecategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AddConstraint(
            model_name='articleproduct',
            constraint=models.UniqueConstraint(fields=('article', 'product'), name='magazine_unique_article_product'),
        ),
        migrations.AddConstraint(
            model_name='articlerelation',
            constraint=models.UniqueConstraint(fields=('article', 'related_article'), name='magazine_unique_article_relation'),
        ),
        migrations.AddConstraint(
            model_name='articlerelation',
            constraint=models.CheckConstraint(condition=models.Q(('article', models.F('related_article')), _negated=True), name='magazine_article_not_self_related'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_published', '-published_at', '-id'], name='magazine_article_public_idx'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('reading_time__gte', 1)), name='magazine_reading_time_positive'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('is_published', False), ('published_at__isnull', False), _connector='OR'), name='magazine_published_date_required'),
        ),
    ]
