# Generated by Django 5.2.5 on 2026-09-09 06:48

import media_store.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=media_store.fields.UploadImageField(blank=True, upload_to='magazine/covers/%Y/%m/', verbose_name='تصویر اصلی'),
        ),
    ]
